apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuma-alb-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: "gce"
  rules:
    - http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: kuma-alb-mesh-gateway-instance
                port:
                  number: 80