namespace: kuma-alb

image:
  repository: "asia-northeast3-docker.pkg.dev/jieum-dev/jongsoo/fastapi"
  tag: "1.2"
  pullPolicy: IfNotPresent

service:
  name: fastapi-service
  type: ClusterIP
  port: 80

deployment:
  name: fastapi-deployment
  replicas: 1
  port: 80